export const LOAD_BOOKS = "LOAD_BOOKS";
export const LOAD_BOOKS_SUCCESS = "LOAD_BOOKS_SUCCESS";
export const CREATE_BOOKS = "CREATE_BOOKS";
export const CREATE_BOOKS_SUCCESS = "CREATE_BOOKS_SUCCESS";
export const DELETE_BOOK = "DELETE_BOOK";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const UPDATE_BOOK = "UPDATE_BOOK";
export const UPDATE_BOOK_SUCCESS = "UPDATE_BOOK_SUCCESS";

export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
